name: Skills
version: '${project.version}'
main: skills.skills.Skills
api-version: 1.19
commands:
  getSkill:
    description: Gets Skill Information
    usage: /<command>

  levelUp:
    description: Levels Up Skill
    usage: /<command>

  listSkills:
    description: Lists All Skills
    usage: /<command>